[env:nodemcuv2]
platform = espressif8266
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  davylandman/AESLib @ ^2.2.1
  https://github.com/Densaugeo/base64_arduino.git
  adafruit/DHT sensor library @ ^1.4.6
board = nodemcuv2
framework = arduino

;[env:esp32]
;platform = espressif32
;lib_deps =
;  bblanchon/ArduinoJson @ ^6.21.5
;  davylandman/AESLib @ ^2.2.1
;  https://github.com/Densaugeo/base64_arduino.git
;  adafruit/DHT sensor library @ ^1.4.6
;
;board = esp32dev
;framework = arduino
;board_build.partitions = huge_app.csv
;build_type = debug  
